// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.0--rc1
// source: proto/service.proto

package service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EcomService_GetProduct_FullMethodName = "/service.EcomService/GetProduct"
)

// EcomServiceClient is the client API for EcomService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EcomServiceClient interface {
	GetProduct(ctx context.Context, in *ProductRequest, opts ...grpc.CallOption) (*ProductResponse, error)
}

type ecomServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEcomServiceClient(cc grpc.ClientConnInterface) EcomServiceClient {
	return &ecomServiceClient{cc}
}

func (c *ecomServiceClient) GetProduct(ctx context.Context, in *ProductRequest, opts ...grpc.CallOption) (*ProductResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProductResponse)
	err := c.cc.Invoke(ctx, EcomService_GetProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EcomServiceServer is the server API for EcomService service.
// All implementations must embed UnimplementedEcomServiceServer
// for forward compatibility.
type EcomServiceServer interface {
	GetProduct(context.Context, *ProductRequest) (*ProductResponse, error)
	mustEmbedUnimplementedEcomServiceServer()
}

// UnimplementedEcomServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEcomServiceServer struct{}

func (UnimplementedEcomServiceServer) GetProduct(context.Context, *ProductRequest) (*ProductResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProduct not implemented")
}
func (UnimplementedEcomServiceServer) mustEmbedUnimplementedEcomServiceServer() {}
func (UnimplementedEcomServiceServer) testEmbeddedByValue()                     {}

// UnsafeEcomServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EcomServiceServer will
// result in compilation errors.
type UnsafeEcomServiceServer interface {
	mustEmbedUnimplementedEcomServiceServer()
}

func RegisterEcomServiceServer(s grpc.ServiceRegistrar, srv EcomServiceServer) {
	// If the following call pancis, it indicates UnimplementedEcomServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EcomService_ServiceDesc, srv)
}

func _EcomService_GetProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EcomServiceServer).GetProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EcomService_GetProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EcomServiceServer).GetProduct(ctx, req.(*ProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EcomService_ServiceDesc is the grpc.ServiceDesc for EcomService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EcomService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "service.EcomService",
	HandlerType: (*EcomServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetProduct",
			Handler:    _EcomService_GetProduct_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/service.proto",
}
